### PR TITLE
Feature - Azure Pipelines Agent

### PR DESCRIPTION
**Pull request by RossMurr4y**
Impliments container images for an Azure Pipelines Agent. This can be used to undertake build or release workloads within Azure DevOps.

# Running the container
``` bash
docker run -e AZP_URL="https://dev.azure.com/myAwesomeCompany/" -e AZP_TOKEN="1234567890" -e AZP_AGENT_NAME=MyAwesomeAgent azpipeline
```

# A note on stopping the container
When terminated unexpectedly the Agent will remain in the Agent Pool within Azure DevOps. It will then potentially be allocated work to do long after the container is destroyed. When shut-down through `"docker stop <container-name"` however, the agent is cleaned up from the server.

### CODE REVIEW

**Comment by roleyfoley** [comment]
Looks good. So this would be a fixed agent that processes multiple builds and Azure pipelines assumes that you manage the number of active agents using container orchestration ( kubernetes, ecs etc.) ?

**Comment by RossMurr4y** [comment]
Yep. Alternatively we could set an environment variable to an integer, then use it to iteratively create agents? Would allow for any number of agents really. Just depends if you want 1:1 container:agent or 1:many.

**Comment by roleyfoley** [comment]
I'm ok with managing it from the orchestration side of things, its pretty much their job to set how many instances of a container exist. 

My thought was more that in Jenkins you can configure dynamic agents which a provisioned to complete a single job ( or pipeline with multiple jobs in it ) and then its destroyed when finished. This allows you to scale your infrastructure on demand rather than having to scale to a fixed starting point

**Comment by RossMurr4y** [comment]
Looking at the available tasks that Azure Pipelines could run "agentless" (given that its creating the Agent we are going to use), that call would have to be made from an Azure function (a lambda). Theres a pretty limited number of tasks that can be performed "agentless".

**Pull request merged**
